# Change these first
owner: mattgwagner # Your GitHub organization or username, where this repository lives
repo: ideabloom-uptime # The name of this repository

sites:
  - name: Public Website
    url: https://www.ideabloom.io
    type: globalping
  - name: IdeaBloom App
    url: https://app.ideabloom.io
    type: globalping
  - name: IdeaBloom API
    url: https://api.ideabloom.io/api/swagger.json
    type: globalping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ideabloom.io
  # baseUrl: /ideabloom-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Welcome to the IdeaBloom Status Page"
  introMessage: This page provides real-time updates about the availability and uptime of IdeaBloom products. All monitoring and reporting is automated using GitHub Actions—no servers required. For additional details or support, visit our [GitHub repository](https://github.com/mattgwagner/ideabloom-uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
